import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import { ReactNode } from "react";
import Counter from '../components/Counter/Counter';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode; 
}


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Counter />
        {children}
      </body>
    </html>
  );
}


